# Generated by Django 6.0.3 on 2026-04-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0003_realtimeevent_priority'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='realtimeevent',
            new_name='realtime_ev_user_id_2d5e44_idx',
            old_name='realtime_e_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='realtimeevent',
            new_name='realtime_ev_user_id_cfc8b5_idx',
            old_name='realtime_e_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='realtimeevent',
            new_name='realtime_ev_user_id_73f28d_idx',
            old_name='rt_user_dedupe_created',
        ),
    ]
