# Generated by Django 6.0.3 on 2026-04-29 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0004_rename_realtime_e_user_id_idx_realtime_ev_user_id_2d5e44_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('severity', models.CharField(choices=[('sev1', 'SEV1'), ('sev2', 'SEV2'), ('sev3', 'SEV3')], db_index=True, default='sev2', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('summary', models.CharField(db_index=True, default='', max_length=255)),
                ('root_cause', models.TextField(blank=True, default='')),
                ('prevention_action', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident_reviews_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident_reviews_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ops_incident_reviews',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['severity', 'status', 'started_at'], name='ops_inciden_severit_c530ce_idx')],
            },
        ),
    ]
