# Generated by Django 6.0.3 on 2026-04-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_assessmentanswer_client_seq'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='homeworkassignment',
            name='uniq_assessment_hw_classroom_set',
        ),
        migrations.RemoveIndex(
            model_name='assessmentanswer',
            name='assessment__attempt_7a3de9_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentattempt',
            new_name='assessment__student_641170_idx',
            old_name='assessment__student_1c0f09_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentattempt',
            new_name='assessment__student_dbf2cb_idx',
            old_name='assessment__student_status_started_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentattemptauditevent',
            new_name='assessment__attempt_d12f47_idx',
            old_name='assessment_audit_attempt_created_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentattemptauditevent',
            new_name='assessment__event_t_d54f5a_idx',
            old_name='assessment_audit_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmenthomeworkauditevent',
            new_name='assessment__classro_75ed7b_idx',
            old_name='assess_hw_a_classro_9a5a5d_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmenthomeworkauditevent',
            new_name='assessment__assessm_d2d92b_idx',
            old_name='assess_hw_a_assessm_4f4e8b_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmenthomeworkauditevent',
            new_name='assessment__event_t_644887_idx',
            old_name='assess_hw_a_event_t_5c0d37_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentquestion',
            new_name='assessment__assessm_a256a3_idx',
            old_name='assessment__assessm_dcb17a_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentset',
            new_name='assessment__subject_e6803f_idx',
            old_name='assessment__subject_7d4b5e_idx',
        ),
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='assessment__alert_t_279488_idx',
            old_name='assess_sec_alert_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='assessment__source_144322_idx',
            old_name='assess_sec_alert_source_created_idx',
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='source',
            field=models.CharField(choices=[('homework_abuse', 'Homework abuse'), ('homework_abuse_db', 'Homework abuse (DB)'), ('slo', 'SLO')], db_index=True, default='homework_abuse', max_length=40),
        ),
    ]
