# Generated by Django 6.0.3 on 2026-06-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0020_assessmentattempt_question_times'),
        ('questionbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='bank_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='questionbank.bankquestion'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='bank_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='questionbank.bankquestionversion'),
        ),
    ]
