# Generated by Django 6.0.3 on 2026-03-28 21:14

from django.db import migrations


def seed_rbac(apps, schema_editor):
    Permission = apps.get_model("access", "Permission")
    Role = apps.get_model("access", "Role")
    RolePermission = apps.get_model("access", "RolePermission")

    definitions = [
        ("*", "All permissions"),
        ("manage_users", "Manage users"),
        ("manage_roles", "Manage roles and assignments"),
        ("create_test", "Create practice tests"),
        ("edit_test", "Edit practice tests"),
        ("delete_test", "Delete practice tests"),
        ("view_all_tests", "View all practice tests"),
        ("assign_test_access", "Assign test access to students"),
        ("view_english_tests", "View English / R&W tests only"),
        ("view_math_tests", "View math tests only"),
        ("submit_test", "Take and submit tests"),
        ("manage_classrooms", "Manage site-wide groups / classrooms"),
    ]
    perms = {}
    for codename, name in definitions:
        p, _ = Permission.objects.get_or_create(codename=codename, defaults={"name": name})
        if p.name != name:
            p.name = name
            p.save(update_fields=["name"])
        perms[codename] = p

    roles_cfg = [
        ("SUPER_ADMIN", "Super Admin", ["*"]),
        (
            "ADMIN",
            "Admin",
            [
                "manage_users",
                "create_test",
                "edit_test",
                "delete_test",
                "view_all_tests",
                "assign_test_access",
                "manage_classrooms",
            ],
        ),
        ("TEST_ADMIN", "Test Admin", ["create_test"]),
        ("ENGLISH_ADMIN", "English Admin", ["create_test", "edit_test", "view_english_tests"]),
        ("MATH_ADMIN", "Math Admin", ["create_test", "edit_test", "view_math_tests"]),
        ("STUDENT", "Student", ["submit_test"]),
    ]
    for code, name, plist in roles_cfg:
        role, _ = Role.objects.get_or_create(code=code, defaults={"name": name})
        if role.name != name:
            role.name = name
            role.save(update_fields=["name"])
        RolePermission.objects.filter(role=role).delete()
        for pc in plist:
            RolePermission.objects.create(role=role, permission=perms[pc])


def unseed_rbac(apps, schema_editor):
    RolePermission = apps.get_model("access", "RolePermission")
    Role = apps.get_model("access", "Role")
    Permission = apps.get_model("access", "Permission")
    RolePermission.objects.all().delete()
    Role.objects.all().delete()
    Permission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_rbac, unseed_rbac),
    ]
