# Generated by Django 6.0.3 on 2026-04-29 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_user_access'),
        ('classes', '0018_rename_cls_comment_target_idx_class_comme_classro_c2eb0f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useraccess',
            index=models.Index(fields=['user', 'subject'], name='access_user_user_id_8f50fd_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccess',
            index=models.Index(fields=['user', 'subject', 'classroom'], name='access_user_user_id_d95906_idx'),
        ),
    ]
