# Generated by Django 6.0.3 on 2026-06-05 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_useraccess_access_user_user_id_8f50fd_idx_and_more'),
        ('classes', '0019_assignment_practice_test_pack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SUBJECT', 'Subject'), ('RESOURCE', 'Resource')], db_index=True, max_length=8)),
                ('subject', models.CharField(blank=True, db_index=True, help_text='Domain subject (math/english) for SUBJECT grants; NULL for RESOURCE grants.', max_length=16, null=True)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('resource_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('BULK', 'Bulk'), ('CLASSROOM', 'Classroom'), ('PURCHASE', 'Purchase'), ('SYSTEM', 'System / backfill')], db_index=True, default='MANUAL', max_length=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=8)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_access_grants', to='classes.classroom')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_access_grants_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource_access_grants',
            },
        ),
        migrations.CreateModel(
            name='AccessGrantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('EXTENDED', 'Extended'), ('RESTORED', 'Restored'), ('BACKFILLED', 'Backfilled')], db_index=True, max_length=12)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grant_events_authored', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='access.resourceaccessgrant')),
            ],
            options={
                'db_table': 'access_grant_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='resourceaccessgrant',
            index=models.Index(fields=['user', 'status', 'scope'], name='rag_user_status_scope'),
        ),
        migrations.AddIndex(
            model_name='resourceaccessgrant',
            index=models.Index(fields=['user', 'status', 'scope', 'resource_type', 'resource_id'], name='rag_user_resource'),
        ),
        migrations.AddIndex(
            model_name='resourceaccessgrant',
            index=models.Index(fields=['user', 'status', 'scope', 'subject', 'classroom'], name='rag_user_subject'),
        ),
        migrations.AddIndex(
            model_name='resourceaccessgrant',
            index=models.Index(fields=['resource_type', 'resource_id', 'status'], name='rag_resource_reverse'),
        ),
        migrations.AddIndex(
            model_name='resourceaccessgrant',
            index=models.Index(fields=['status', 'expires_at'], name='rag_expiry_sweep'),
        ),
        migrations.AddIndex(
            model_name='resourceaccessgrant',
            index=models.Index(fields=['classroom', 'status'], name='rag_classroom_status'),
        ),
        migrations.AddConstraint(
            model_name='resourceaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resource_id__isnull', True), ('resource_type__isnull', True), ('scope', 'SUBJECT'), ('subject__isnull', False)), models.Q(('resource_id__isnull', False), ('resource_type__isnull', False), ('scope', 'RESOURCE'), ('subject__isnull', True)), _connector='OR'), name='rag_scope_shape'),
        ),
        migrations.AddConstraint(
            model_name='resourceaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('classroom__isnull', True), ('scope', 'SUBJECT'), ('status', 'ACTIVE')), fields=('user', 'subject'), name='rag_uniq_active_subject_global'),
        ),
        migrations.AddConstraint(
            model_name='resourceaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('classroom__isnull', False), ('scope', 'SUBJECT'), ('status', 'ACTIVE')), fields=('user', 'subject', 'classroom'), name='rag_uniq_active_subject_classroom'),
        ),
        migrations.AddConstraint(
            model_name='resourceaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('classroom__isnull', True), ('scope', 'RESOURCE'), ('status', 'ACTIVE')), fields=('user', 'resource_type', 'resource_id'), name='rag_uniq_active_resource_global'),
        ),
        migrations.AddConstraint(
            model_name='resourceaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('classroom__isnull', False), ('scope', 'RESOURCE'), ('status', 'ACTIVE')), fields=('user', 'resource_type', 'resource_id', 'classroom'), name='rag_uniq_active_resource_classroom'),
        ),
        migrations.AddIndex(
            model_name='accessgrantevent',
            index=models.Index(fields=['grant', 'created_at'], name='age_grant_created'),
        ),
        migrations.AddIndex(
            model_name='accessgrantevent',
            index=models.Index(fields=['action', 'created_at'], name='age_action_created'),
        ),
    ]
