"""Prometheus text exposition for exam-engine counters (no extra dependencies)."""

from __future__ import annotations

from django.utils import timezone

from .metrics import get_counter


def render_exams_prometheus_text() -> str:
    lines: list[str] = [
        "# HELP exams_attempt_submit_module_total Module submits accepted.",
        "# TYPE exams_attempt_submit_module_total counter",
        f"exams_attempt_submit_module_total {get_counter('submit_module')}",
        "# HELP exams_attempt_idempotency_replay_total Idempotency key replays.",
        "# TYPE exams_attempt_idempotency_replay_total counter",
        f"exams_attempt_idempotency_replay_total {get_counter('idempotency_replay')}",
        "# HELP exams_attempt_submit_duplicate_prevented_total Duplicate submits prevented by locking/idempotency.",
        "# TYPE exams_attempt_submit_duplicate_prevented_total counter",
        f"exams_attempt_submit_duplicate_prevented_total {get_counter('submit_duplicate_prevented')}",
        "# HELP exams_attempt_version_conflict_total Optimistic concurrency conflicts.",
        "# TYPE exams_attempt_version_conflict_total counter",
        f"exams_attempt_version_conflict_total {get_counter('version_conflict')}",
        "# HELP exams_attempt_scoring_enqueued_total Attempts transitioned to SCORING.",
        "# TYPE exams_attempt_scoring_enqueued_total counter",
        f"exams_attempt_scoring_enqueued_total {get_counter('scoring_enqueued')}",
        "# HELP exams_attempt_scoring_completed_total Attempts completed from scoring.",
        "# TYPE exams_attempt_scoring_completed_total counter",
        f"exams_attempt_scoring_completed_total {get_counter('scoring_completed')}",
        "# HELP exams_active_attempt_duplicates_prevented_total Duplicate active attempts prevented by DB constraint retry.",
        "# TYPE exams_active_attempt_duplicates_prevented_total counter",
        f"exams_active_attempt_duplicates_prevented_total {get_counter('active_attempt_duplicates_prevented')}",
        "# HELP exams_integrity_repairs_applied_total Integrity repair mutations applied (best-effort).",
        "# TYPE exams_integrity_repairs_applied_total counter",
        f"exams_integrity_repairs_applied_total {get_counter('integrity_repairs_applied')}",
        "# HELP exams_wrong_staff_endpoint_total Staff consoles using public endpoints.",
        "# TYPE exams_wrong_staff_endpoint_total counter",
        f"exams_wrong_staff_endpoint_total {get_counter('wrong_staff_endpoint_total')}",
        "# HELP exams_forbidden_admin_route_total Forbidden console route attempts (host guard).",
        "# TYPE exams_forbidden_admin_route_total counter",
        f"exams_forbidden_admin_route_total {get_counter('forbidden_admin_route_total')}",
        "# HELP exams_metrics_generated_at Unix timestamp when metrics rendered.",
        "# TYPE exams_metrics_generated_at gauge",
        f"exams_metrics_generated_at {int(timezone.now().timestamp())}",
        "# HELP slo_api_4xx_total API 4xx responses (best-effort, AppError+DRF handler).",
        "# TYPE slo_api_4xx_total counter",
        f"slo_api_4xx_total {get_counter('slo_api_4xx_total')}",
        "# HELP slo_api_5xx_total API 5xx responses (best-effort, AppError+DRF handler).",
        "# TYPE slo_api_5xx_total counter",
        f"slo_api_5xx_total {get_counter('slo_api_5xx_total')}",
        "# HELP slo_exam_start_ok_total Exam attempt create ok (POST attempts/).",
        "# TYPE slo_exam_start_ok_total counter",
        f"slo_exam_start_ok_total {get_counter('slo_exam_start_ok_total')}",
        "# HELP slo_exam_start_fail_total Exam attempt create failed (POST attempts/).",
        "# TYPE slo_exam_start_fail_total counter",
        f"slo_exam_start_fail_total {get_counter('slo_exam_start_fail_total')}",
        "# HELP slo_exam_start_latency_ms_sum Sum of exam attempt create latency (ms).",
        "# TYPE slo_exam_start_latency_ms_sum counter",
        f"slo_exam_start_latency_ms_sum {get_counter('slo_exam_start_latency_ms_sum')}",
        "# HELP slo_exam_start_latency_ms_count Count of exam attempt create samples.",
        "# TYPE slo_exam_start_latency_ms_count counter",
        f"slo_exam_start_latency_ms_count {get_counter('slo_exam_start_latency_ms_count')}",
        "# HELP slo_exam_engine_start_ok_total Exam runner start ok (POST attempts/<id>/start/).",
        "# TYPE slo_exam_engine_start_ok_total counter",
        f"slo_exam_engine_start_ok_total {get_counter('slo_exam_engine_start_ok_total')}",
        "# HELP slo_exam_engine_start_fail_total Exam runner start failed (POST attempts/<id>/start/).",
        "# TYPE slo_exam_engine_start_fail_total counter",
        f"slo_exam_engine_start_fail_total {get_counter('slo_exam_engine_start_fail_total')}",
        "# HELP slo_exam_engine_start_latency_ms_sum Sum of exam runner start latency (ms).",
        "# TYPE slo_exam_engine_start_latency_ms_sum counter",
        f"slo_exam_engine_start_latency_ms_sum {get_counter('slo_exam_engine_start_latency_ms_sum')}",
        "# HELP slo_exam_engine_start_latency_ms_count Count of exam runner start samples.",
        "# TYPE slo_exam_engine_start_latency_ms_count counter",
        f"slo_exam_engine_start_latency_ms_count {get_counter('slo_exam_engine_start_latency_ms_count')}",
        "# HELP slo_exam_resume_ok_total Attempt resume ok (POST attempts/<id>/resume/).",
        "# TYPE slo_exam_resume_ok_total counter",
        f"slo_exam_resume_ok_total {get_counter('slo_exam_resume_ok_total')}",
        "# HELP slo_exam_resume_fail_total Attempt resume failed (POST attempts/<id>/resume/).",
        "# TYPE slo_exam_resume_fail_total counter",
        f"slo_exam_resume_fail_total {get_counter('slo_exam_resume_fail_total')}",
        "# HELP slo_exam_resume_latency_ms_sum Sum of attempt resume latency (ms).",
        "# TYPE slo_exam_resume_latency_ms_sum counter",
        f"slo_exam_resume_latency_ms_sum {get_counter('slo_exam_resume_latency_ms_sum')}",
        "# HELP slo_exam_resume_latency_ms_count Count of attempt resume samples.",
        "# TYPE slo_exam_resume_latency_ms_count counter",
        f"slo_exam_resume_latency_ms_count {get_counter('slo_exam_resume_latency_ms_count')}",
        "# HELP slo_module_submit_ok_total Exam module submit ok (POST attempts/<id>/submit_module/).",
        "# TYPE slo_module_submit_ok_total counter",
        f"slo_module_submit_ok_total {get_counter('slo_module_submit_ok_total')}",
        "# HELP slo_module_submit_fail_total Exam module submit failed (POST attempts/<id>/submit_module/).",
        "# TYPE slo_module_submit_fail_total counter",
        f"slo_module_submit_fail_total {get_counter('slo_module_submit_fail_total')}",
        "# HELP slo_module_submit_latency_ms_sum Sum of module submit latency (ms).",
        "# TYPE slo_module_submit_latency_ms_sum counter",
        f"slo_module_submit_latency_ms_sum {get_counter('slo_module_submit_latency_ms_sum')}",
        "# HELP slo_module_submit_latency_ms_count Count of module submit samples.",
        "# TYPE slo_module_submit_latency_ms_count counter",
        f"slo_module_submit_latency_ms_count {get_counter('slo_module_submit_latency_ms_count')}",
        "# HELP slo_homework_assign_ok_total Homework assign ok (POST assessments homework assign).",
        "# TYPE slo_homework_assign_ok_total counter",
        f"slo_homework_assign_ok_total {get_counter('slo_homework_assign_ok_total')}",
        "# HELP slo_homework_assign_fail_total Homework assign failed (POST assessments homework assign).",
        "# TYPE slo_homework_assign_fail_total counter",
        f"slo_homework_assign_fail_total {get_counter('slo_homework_assign_fail_total')}",
        "# HELP slo_homework_assign_latency_ms_sum Sum of homework assign latency (ms).",
        "# TYPE slo_homework_assign_latency_ms_sum counter",
        f"slo_homework_assign_latency_ms_sum {get_counter('slo_homework_assign_latency_ms_sum')}",
        "# HELP slo_homework_assign_latency_ms_count Count of homework assign samples.",
        "# TYPE slo_homework_assign_latency_ms_count counter",
        f"slo_homework_assign_latency_ms_count {get_counter('slo_homework_assign_latency_ms_count')}",
        "# HELP slo_login_ok_total Successful logins (cookie auth).",
        "# TYPE slo_login_ok_total counter",
        f"slo_login_ok_total {get_counter('slo_login_ok_total')}",
        "# HELP slo_login_fail_total Failed logins (cookie auth).",
        "# TYPE slo_login_fail_total counter",
        f"slo_login_fail_total {get_counter('slo_login_fail_total')}",
        "# HELP slo_login_latency_ms_sum Sum of login latency (ms).",
        "# TYPE slo_login_latency_ms_sum counter",
        f"slo_login_latency_ms_sum {get_counter('slo_login_latency_ms_sum')}",
        "# HELP slo_login_latency_ms_count Count of login latency samples.",
        "# TYPE slo_login_latency_ms_count counter",
        f"slo_login_latency_ms_count {get_counter('slo_login_latency_ms_count')}",
    ]
    return "\n".join(lines) + "\n"

