# Generated by Django 5.2.10 on 2026-03-07 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, help_text='e.g., International Form C', max_length=200)),
                ('test_date', models.CharField(blank=True, help_text='e.g., March 2025', max_length=100)),
                ('subject', models.CharField(choices=[('READING_WRITING', 'Reading & Writing'), ('MATH', 'Math')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'practice_tests',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_order', models.IntegerField(choices=[(1, 'Module 1'), (2, 'Module 2')])),
                ('time_limit_minutes', models.IntegerField()),
                ('practice_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='exams.practicetest')),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['module_order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('MATH', 'Math'), ('READING', 'Reading'), ('WRITING', 'Writing')], db_index=True, max_length=10)),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('option_a', models.CharField(blank=True, max_length=255)),
                ('option_b', models.CharField(blank=True, max_length=255)),
                ('option_c', models.CharField(blank=True, max_length=255)),
                ('option_d', models.CharField(blank=True, max_length=255)),
                ('correct_answers', models.CharField(help_text="For math input, separate multiple correct answers with a comma. e.g. '2/3, 0.666, 0.667'", max_length=255)),
                ('is_math_input', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.module')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('current_module_start_time', models.DateTimeField(blank=True, null=True)),
                ('module_answers', models.JSONField(blank=True, default=dict)),
                ('flagged_questions', models.JSONField(blank=True, default=dict)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('completed_modules', models.ManyToManyField(blank=True, related_name='completed_attempts', to='exams.module')),
                ('current_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.module')),
                ('practice_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.practicetest')),
            ],
            options={
                'db_table': 'test_attempts',
            },
        ),
    ]
