# Generated by Django 5.2.10 on 2026-03-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['practice_test', 'module_order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='question_prompt',
            field=models.TextField(blank=True, help_text='Secondary text displayed above answer choices.'),
        ),
    ]
