# Generated by Django 5.2.10 on 2026-03-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_module_module_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicetest',
            name='test_date',
        ),
        migrations.AddField(
            model_name='practicetest',
            name='practice_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
