# Generated by Django 5.2.10 on 2026-03-18 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_practicetest_test_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetest',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=10, help_text='Score weight for this question'),
        ),
    ]
