# Generated by Django 6.0.3 on 2026-03-19 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_question_options_question_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testattempt',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='practicetest',
            name='assigned_users',
        ),
        migrations.RemoveField(
            model_name='practicetest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='practicetest',
            name='practice_date',
        ),
        migrations.RemoveField(
            model_name='practicetest',
            name='title',
        ),
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, help_text='e.g., International Form C', max_length=200)),
                ('practice_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mock_exams',
            },
        ),
        migrations.AddField(
            model_name='practicetest',
            name='mock_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='exams.mockexam'),
        ),
    ]
