# Generated by Django 5.2.10 on 2026-03-21 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_testattempt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockexam',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='practicetest',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
