# Generated by Django 5.2.10 on 2026-03-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_remove_mockexam_assigned_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetest',
            name='form_type',
            field=models.CharField(choices=[('INTERNATIONAL', 'International Form'), ('US', 'US Form')], db_index=True, default='INTERNATIONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='practicetest',
            name='label',
            field=models.CharField(blank=True, help_text='e.g., A, B, C, D', max_length=10),
        ),
    ]
