# Generated by Django 5.2.10 on 2026-03-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_practicetest_form_type_practicetest_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
    ]
