# Generated by Django 6.0.3 on 2026-03-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_portal_mock_sat_to_pastpapers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexam',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, students with portal access see this timed mock. Pastpaper practice uses separate standalone tests.'),
        ),
        migrations.AlterField(
            model_name='mockexam',
            name='title',
            field=models.CharField(db_index=True, help_text='Timed diagnostic mock (staff-authored). Not built from pastpaper practice items.', max_length=200),
        ),
        migrations.AlterField(
            model_name='practicetest',
            name='mock_exam',
            field=models.ForeignKey(blank=True, help_text='NULL = pastpaper / practice library. If set, this row is a mock-only section (staff-built under that mock, never linked from pastpapers).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='exams.mockexam'),
        ),
    ]
