# Generated by Django 6.0.3 on 2026-04-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0033_unique_active_attempt_per_student_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='current_state',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('MODULE_1_ACTIVE', 'Module 1 active'), ('MODULE_1_SUBMITTED', 'Module 1 submitted'), ('MODULE_2_ACTIVE', 'Module 2 active'), ('MODULE_2_SUBMITTED', 'Module 2 submitted'), ('SCORING', 'Scoring'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], db_index=True, default='NOT_STARTED', max_length=24),
        ),
    ]
