# Generated by Django 6.0.3 on 2026-05-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0039_module_question_order_high_water'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attemptengineaudit',
            new_name='exams_attem_attempt_8fe07f_idx',
            old_name='exams_audit_att_cre',
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='abandoned_checkpoint_state',
            field=models.CharField(blank=True, default='', help_text='Snapshot of current_state persisted when transitioning to ABANDONED (authoritative resume target; empty/null => restart module 1).', max_length=24, null=True),
        ),
    ]
