# Generated by Django 6.0.3 on 2026-05-21 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0042_pastpaperpack_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTestPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', help_text='Practice test pack title shown in admin and student lists.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description for the practice test pack.')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Only published packs are visible to students.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_practice_test_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_test_packs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='practicetest',
            name='practice_test_pack',
            field=models.ForeignKey(blank=True, help_text='When set, this section belongs to a custom practice test pack (not a pastpaper).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.practicetestpack'),
        ),
    ]
