# Generated by Django 6.0.3 on 2026-06-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0044_testattempt_pause_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='midterm_scoring_scale',
            field=models.CharField(choices=[('SCALE_100', '100-point (percentage)'), ('SCALE_800', '800-point (SAT scaled)')], default='SCALE_100', help_text='Only used when kind=MIDTERM. Controls the final score scale.', max_length=20),
        ),
    ]
