# Generated by Django 6.0.3 on 2026-06-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0024_drop_pastpaperpack'),
        ('exams', '0047_practicetest_standalone_section_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='practicetest',
            name='uniq_pastpaper_pack_subject',
        ),
        migrations.RemoveField(
            model_name='practicetest',
            name='pastpaper_detached_at',
        ),
        migrations.RemoveField(
            model_name='practicetest',
            name='pastpaper_detached_pack_id',
        ),
        migrations.RemoveField(
            model_name='practicetest',
            name='pastpaper_pack',
        ),
        migrations.DeleteModel(
            name='PastpaperPack',
        ),
    ]
