# Generated by Django 6.0.3 on 2026-06-02 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('ENGLISH', 'English'), ('MATH', 'Math')], db_index=True, default='ENGLISH', max_length=16)),
                ('passage_text', models.TextField()),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manually authored'), ('PDF_IMPORT', 'PDF import'), ('MIGRATED_EXAM', 'Migrated from exam engine'), ('MIGRATED_ASSESSMENT', 'Migrated from assessments'), ('COLLEGE_BOARD', 'College Board'), ('OTHER', 'Other')], default='MANUAL', max_length=32)),
                ('source_reference', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'qb_passages',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QbIdCounter',
            fields=[
                ('subject', models.CharField(choices=[('ENGLISH', 'English'), ('MATH', 'Math')], max_length=16, primary_key=True, serialize=False)),
                ('last_value', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'qb_id_counters',
            },
        ),
        migrations.CreateModel(
            name='BankDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENGLISH', 'English'), ('MATH', 'Math')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(help_text="Stable machine code, e.g. 'algebra'.", max_length=64)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'qb_domains',
                'ordering': ['subject', 'display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'name'), name='uniq_qb_domain_subject_name'), models.UniqueConstraint(fields=('subject', 'code'), name='uniq_qb_domain_subject_code')],
            },
        ),
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qb_id', models.CharField(db_index=True, editable=False, help_text='Permanent identifier, e.g. QB-ENG-000001. Assigned once, never changes.', max_length=32, unique=True)),
                ('subject', models.CharField(choices=[('ENGLISH', 'English'), ('MATH', 'Math')], db_index=True, max_length=16)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='', max_length=8)),
                ('status', models.CharField(choices=[('IMPORTED', 'Imported (raw)'), ('TRIAGE', 'In triage (awaiting classification)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], db_index=True, default='IMPORTED', max_length=16)),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple choice'), ('STUDENT_PRODUCED', 'Student-produced response (grid-in)'), ('SHORT_TEXT', 'Short text'), ('NUMERIC', 'Numeric'), ('BOOLEAN', 'True/False')], db_index=True, max_length=32)),
                ('question_text', models.TextField()),
                ('question_prompt', models.TextField(blank=True, default='', help_text='Secondary text above the choices.')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_bank/questions/')),
                ('option_a', models.TextField(blank=True, default='')),
                ('option_b', models.TextField(blank=True, default='')),
                ('option_c', models.TextField(blank=True, default='')),
                ('option_d', models.TextField(blank=True, default='')),
                ('option_a_image', models.ImageField(blank=True, null=True, upload_to='question_bank/options/')),
                ('option_b_image', models.ImageField(blank=True, null=True, upload_to='question_bank/options/')),
                ('option_c_image', models.ImageField(blank=True, null=True, upload_to='question_bank/options/')),
                ('option_d_image', models.ImageField(blank=True, null=True, upload_to='question_bank/options/')),
                ('correct_answer', models.JSONField(blank=True, default=None, null=True)),
                ('explanation', models.TextField(blank=True, default='')),
                ('points', models.PositiveIntegerField(default=1)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manually authored'), ('PDF_IMPORT', 'PDF import'), ('MIGRATED_EXAM', 'Migrated from exam engine'), ('MIGRATED_ASSESSMENT', 'Migrated from assessments'), ('COLLEGE_BOARD', 'College Board'), ('OTHER', 'Other')], db_index=True, default='MANUAL', max_length=32)),
                ('source_reference', models.CharField(blank=True, default='', max_length=512)),
                ('suggested_difficulty', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='', max_length=8)),
                ('suggestion_confidence', models.FloatField(blank=True, null=True)),
                ('suggestion_model', models.CharField(blank=True, default='', max_length=128)),
                ('suggestion_rationale', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_bank_questions', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questionbank.bankdomain')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questionbank.bankpassage')),
                ('suggested_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_for_questions', to='questionbank.bankdomain')),
            ],
            options={
                'db_table': 'qb_questions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankQuestionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(db_index=True)),
                ('snapshot_json', models.JSONField()),
                ('snapshot_checksum', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bank_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='questionbank.bankquestion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_bank_question_versions', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_versions', to='questionbank.bankquestionversion')),
            ],
            options={
                'db_table': 'qb_question_versions',
                'ordering': ['bank_question_id', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questionbank.bankquestionversion'),
        ),
        migrations.CreateModel(
            name='BankSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(help_text="Stable machine code, e.g. 'linear-functions'.", max_length=64)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='questionbank.bankdomain')),
            ],
            options={
                'db_table': 'qb_skills',
                'ordering': ['domain', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questionbank.bankskill'),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='suggested_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_for_questions', to='questionbank.bankskill'),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manually authored'), ('PDF_IMPORT', 'PDF import'), ('MIGRATED_EXAM', 'Migrated from exam engine'), ('MIGRATED_ASSESSMENT', 'Migrated from assessments'), ('COLLEGE_BOARD', 'College Board'), ('OTHER', 'Other')], default='PDF_IMPORT', max_length=32)),
                ('filename', models.CharField(blank=True, default='', max_length=512)),
                ('source_reference', models.CharField(blank=True, default='', help_text='Free-form origin pointer (URL, original document id, etc.).', max_length=512)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing'), ('READY', 'Ready for review'), ('PROMOTED', 'Promoted to bank'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('total_candidates', models.PositiveIntegerField(default=0)),
                ('promoted_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qb_import_batches',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questionbank.importbatch'),
        ),
        migrations.AddField(
            model_name='bankpassage',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to='questionbank.importbatch'),
        ),
        migrations.AddConstraint(
            model_name='bankquestionversion',
            constraint=models.UniqueConstraint(fields=('bank_question', 'version_number'), name='uniq_qb_question_version_number'),
        ),
        migrations.AddConstraint(
            model_name='bankskill',
            constraint=models.UniqueConstraint(fields=('domain', 'name'), name='uniq_qb_skill_domain_name'),
        ),
        migrations.AddConstraint(
            model_name='bankskill',
            constraint=models.UniqueConstraint(fields=('domain', 'code'), name='uniq_qb_skill_domain_code'),
        ),
        migrations.AddIndex(
            model_name='bankquestion',
            index=models.Index(fields=['subject', 'status'], name='qb_question_subject_2938d7_idx'),
        ),
        migrations.AddIndex(
            model_name='bankquestion',
            index=models.Index(fields=['status', 'domain', 'skill'], name='qb_question_status_75dd5b_idx'),
        ),
        migrations.AddIndex(
            model_name='bankquestion',
            index=models.Index(fields=['content_hash'], name='qb_question_content_3f3349_idx'),
        ),
        migrations.AddIndex(
            model_name='bankpassage',
            index=models.Index(fields=['subject', 'content_hash'], name='qb_passages_subject_2ebff0_idx'),
        ),
    ]
