# Generated by Django 6.0.3 on 2026-06-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(blank=True, choices=[('ENGLISH', 'English'), ('MATH', 'Math')], default='', max_length=16)),
                ('raw_domain', models.CharField(blank=True, default='', max_length=255)),
                ('raw_skill', models.CharField(blank=True, default='', max_length=255)),
                ('raw_difficulty', models.CharField(blank=True, default='', max_length=64)),
                ('passage_text', models.TextField(blank=True, default='')),
                ('question_text', models.TextField(blank=True, default='')),
                ('option_a', models.TextField(blank=True, default='')),
                ('option_b', models.TextField(blank=True, default='')),
                ('option_c', models.TextField(blank=True, default='')),
                ('option_d', models.TextField(blank=True, default='')),
                ('correct_answer', models.JSONField(blank=True, default=None, null=True)),
                ('explanation', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DUPLICATE', 'Duplicate')], db_index=True, default='VALID', max_length=16)),
                ('validation_messages', models.JSONField(blank=True, default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='questionbank.importbatch')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_duplicates', to='questionbank.bankquestion')),
                ('promoted_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_candidates', to='questionbank.bankquestion')),
            ],
            options={
                'db_table': 'qb_import_candidates',
                'ordering': ['batch_id', 'order', 'id'],
                'indexes': [models.Index(fields=['batch', 'validation_status'], name='qb_import_c_batch_i_1d2cc6_idx')],
            },
        ),
    ]
