# Generated by Django 6.0.3 on 2026-06-20 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0002_importcandidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankquestion',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='student_answer',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='importcandidate',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='importcandidate',
            name='question_image',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='importcandidate',
            name='student_answer',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='bankquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_id',), name='uniq_qb_external_id_when_set'),
        ),
    ]
