# Generated by Django 6.0.3 on 2026-06-20 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0003_bankquestion_external_id_bankquestion_student_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, default='', max_length=255)),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bank_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='questionbank.bankquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_question_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qb_question_attempts',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='qb_question_user_id_89ee5f_idx')],
            },
        ),
    ]
