# Generated by Django 6.0.3 on 2026-04-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='uservocabularyprogress',
            new_name='vocabulary__user_id_1ea9d6_idx',
            old_name='vocab_user__status_3cdb1d_idx',
        ),
        migrations.RenameIndex(
            model_name='uservocabularyprogress',
            new_name='vocabulary__user_id_e9efae_idx',
            old_name='vocab_user__next_re_7cfd08_idx',
        ),
        migrations.RenameIndex(
            model_name='uservocabularyreviewevent',
            new_name='vocabulary__user_id_ba88d4_idx',
            old_name='vocab_event_user_id_4df692_idx',
        ),
        migrations.RenameIndex(
            model_name='uservocabularyreviewevent',
            new_name='vocabulary__user_id_c8ea26_idx',
            old_name='vocab_event_user_id_6a9a7e_idx',
        ),
    ]
