# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0003_vocab_spaced_repetition"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwordprogress",
            name="introduced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userwordprogress",
            name="learning_phase",
            field=models.BooleanField(default=True),
        ),
    ]
