# Generated by Django 6.0.3 on 2026-04-04 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_teacher_and_telegram_chat_id'),
        ('exams', '0023_pastpaperpack_practicetest_pastpaper_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='pastpaper_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_assignments', to='exams.pastpaperpack'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='practice_test_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
