# Generated by Django 6.0.3 on 2026-04-05 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_assignment_pastpaper_pack_bundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='lesson_days',
            field=models.CharField(choices=[('ODD', 'Odd days'), ('EVEN', 'Even days')], db_index=True, max_length=10),
        ),
        migrations.CreateModel(
            name='AssignmentExtraAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homework_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_attachments', to='classes.assignment')),
            ],
            options={
                'db_table': 'class_assignment_extra_attachments',
                'ordering': ['id'],
            },
        ),
    ]
