# Generated by Django 6.0.3 on 2026-04-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_alter_classroom_schedule_summary_default'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classcomment',
            new_name='class_comme_classro_c2eb0f_idx',
            old_name='cls_comment_target_idx',
        ),
        migrations.RenameIndex(
            model_name='classroomstreamitem',
            new_name='classroom_s_classro_956173_idx',
            old_name='cls_stream_clsroom_created',
        ),
    ]
