# Generated by Django 6.0.3 on 2026-05-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_rename_cls_comment_target_idx_class_comme_classro_c2eb0f_idx_and_more'),
        ('exams', '0043_practicetestpack_practicetest_practice_test_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='practice_test_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_assignments', to='exams.practicetestpack'),
        ),
    ]
