# Generated by Django 6.0.3 on 2026-06-13 19:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_assignment_practice_test_pack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.CharField(choices=[('HOMEWORK', 'Homework'), ('CLASSWORK', 'Classwork'), ('QUIZ', 'Quiz'), ('PARTICIPATION', 'Participation'), ('PRACTICE_TEST', 'Practice test'), ('MOCK_EXAM', 'Mock exam'), ('PAST_PAPER', 'Past paper')], db_index=True, default='HOMEWORK', help_text='Routes the result to SAT or Academic ranking. See BUSINESS-ARCHITECTURE §3.4.', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Points this work is graded out of; required to normalize teacher grades for Academic ranking.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='classroommembership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='submissionreview',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='classroommembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin (legacy owner)'), ('OWNER', 'Owner'), ('TEACHER', 'Teacher'), ('TA', 'Teaching Assistant'), ('STUDENT', 'Student')], db_index=True, max_length=10),
        ),
        migrations.CreateModel(
            name='AcademicWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_homework', models.DecimalField(decimal_places=2, default=Decimal('0.35'), max_digits=4)),
                ('w_quiz', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4)),
                ('w_classwork', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=4)),
                ('w_participation', models.DecimalField(decimal_places=2, default=Decimal('0.15'), max_digits=4)),
                ('w_attendance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('missing_as_zero', models.BooleanField(default=False, help_text='Teacher opt-in: count past-due ungraded work as 0 (§3.2).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_weights', to='classes.classroom')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_academic_weights',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('lesson_index', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FINALIZED', 'Finalized')], db_index=True, default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='classes.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_attendance_sessions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], db_index=True, max_length=10)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='classes.attendancesession')),
            ],
            options={
                'db_table': 'classroom_attendance_records',
            },
        ),
        migrations.CreateModel(
            name='ClassroomRankingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_mode', models.CharField(choices=[('FULL', 'Full'), ('ANONYMOUS', 'Anonymous'), ('HIDDEN', 'Hidden')], default='FULL', max_length=10)),
                ('hide_score_values', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_config', to='classes.classroom')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_ranking_config',
            },
        ),
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SAT', 'SAT'), ('ACADEMIC', 'Academic')], db_index=True, max_length=10)),
                ('scope', models.CharField(choices=[('CLASSROOM', 'Classroom')], default='CLASSROOM', max_length=12)),
                ('period_key', models.CharField(db_index=True, help_text="e.g. '2026-06-13' (daily snapshot) or cycle id", max_length=32)),
                ('rank', models.PositiveIntegerField()),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('percentile', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('trend', models.CharField(blank=True, choices=[('IMPROVING', 'Improving'), ('STABLE', 'Stable'), ('DECLINING', 'Declining')], max_length=10, null=True)),
                ('confidence', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=8, null=True)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(db_index=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_snapshots', to='classes.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_ranking_snapshots',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_total', models.PositiveIntegerField(help_text='Target full SAT score, 400–1600')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_goals', to='classes.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sat_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_student_goals',
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['classroom', 'date'], name='classroom_a_classro_c178d0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'status'], name='classroom_a_student_9a1097_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student')},
        ),
        migrations.AddIndex(
            model_name='rankingsnapshot',
            index=models.Index(fields=['classroom', 'kind', 'period_key', 'rank'], name='classroom_r_classro_f8ef38_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingsnapshot',
            index=models.Index(fields=['classroom', 'kind', 'student', 'period_key'], name='classroom_r_classro_56511b_idx'),
        ),
        migrations.AddConstraint(
            model_name='rankingsnapshot',
            constraint=models.UniqueConstraint(fields=('classroom', 'kind', 'period_key', 'student'), name='uniq_ranking_snapshot_per_period'),
        ),
        migrations.AddConstraint(
            model_name='studentgoal',
            constraint=models.UniqueConstraint(fields=('student', 'classroom'), name='uniq_goal_per_student_classroom'),
        ),
    ]
