# Generated by Django 6.0.3 on 2026-06-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_assignment_archived_at_assignment_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionreview',
            name='is_auto',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
