# Generated by Django 6.0.3 on 2026-06-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0023_classroom_description_classroommaterial'),
        # Must run AFTER the exams backfill that reads Assignment.pastpaper_pack into
        # practice_test_ids — otherwise the FK is gone before the data is migrated.
        ('exams', '0047_practicetest_standalone_section_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='pastpaper_pack',
        ),
    ]
