# Generated by Django 6.0.3 on 2026-03-28 21:14

import django.db.models.deletion
from django.db import migrations, models


def forwards_populate_system_role(apps, schema_editor):
    User = apps.get_model("users", "User")
    Role = apps.get_model("access", "Role")
    roles = {r.code: r for r in Role.objects.all()}
    for u in User.objects.all().iterator():
        if u.system_role_id:
            continue
        if getattr(u, "is_superuser", False):
            u.system_role = roles.get("SUPER_ADMIN") or roles.get("ADMIN")
        elif getattr(u, "role", None) == "ADMIN":
            u.system_role = roles.get("ADMIN")
        else:
            u.system_role = roles.get("STUDENT")
        if u.system_role_id:
            u.save(update_fields=["system_role"])


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_seed_rbac"),
        ("users", "0004_user_profile_exam_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="system_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="access.role",
            ),
        ),
        migrations.RunPython(forwards_populate_system_role, backwards_noop),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AlterField(
            model_name="user",
            name="system_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="access.role",
            ),
        ),
    ]
