# Generated by Django 6.0.3 on 2026-04-03 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_test_admin_library_perms'),
        ('users', '0006_sync_django_staff_from_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='E.164-style or local digits; optional, unique when set (e.g. for Telegram users).', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='access.role'),
        ),
    ]
