# Generated by Django 6.0.3 on 2026-06-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_security_audit_and_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_english',
            field=models.PositiveIntegerField(blank=True, help_text='Target English/Reading-Writing score (200–800)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='target_math',
            field=models.PositiveIntegerField(blank=True, help_text='Target Math score (200–800)', null=True),
        ),
    ]
