/* eslint-disable */
// @generated by scripts/generate-openapi-client.mjs
// DO NOT EDIT MANUALLY

import api from "@/lib/api";
import type { paths } from "@/lib/openapi-types";

type HttpMethod = "get" | "post" | "put" | "patch" | "delete";
type PathKey = keyof paths & string;
type MethodForPath<P extends PathKey> = Extract<keyof paths[P], HttpMethod>;

type JsonResponseFor<P extends PathKey, M extends MethodForPath<P>> =
  paths[P][M] extends { responses: infer R }
    ? R extends Record<number, any>
      ? 200 extends keyof R
        ? R[200] extends { content: { "application/json": infer T } }
          ? T
          : unknown
        : 201 extends keyof R
          ? R[201] extends { content: { "application/json": infer T } }
            ? T
            : unknown
          : 204 extends keyof R
            ? void
            : unknown
      : unknown
    : unknown;

type JsonRequestBodyFor<P extends PathKey, M extends MethodForPath<P>> =
  paths[P][M] extends { requestBody: { content: { "application/json": infer T } } } ? T : never;

type QueryParamsFor<P extends PathKey, M extends MethodForPath<P>> =
  paths[P][M] extends { parameters: { query?: infer Q } } ? Q : never;

export async function openapiRequest<P extends PathKey, M extends MethodForPath<P>>(args: {
  path: P;
  method: M;
  url: string;
  query?: QueryParamsFor<P, M>;
  json?: JsonRequestBodyFor<P, M>;
  headers?: Record<string, string>;
}): Promise<JsonResponseFor<P, M>> {
  const { method, url, json, query, headers } = args;
  const r =
    method === "get" || method === "delete"
      ? await api.request({ method, url, params: query as any, headers })
      : await api.request({ method, url, params: query as any, data: json as any, headers });
  return r.data as any;
}
